# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cf9c01131df8752d3c309fcc1b89ebcad71ad6f4e1a1d8ed86360eb758e7b73104772a3c5c860e1c128480dcc9967f67fc2213e420c93850371f9e794c20d1c

test:
  secret_key_base: ddb6a36a74055a5849afa4d34417fda9e573176292a24d0ec843aa66b28d9f68e35e5125b6ae6fd669d7e4719b5ca2ba120c85f1a11d47d2aa3c7768dee4d525

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
